HAI
	HOW IZ I getPow YR X AN YR Y AN YR Z AN YR B
		
		VISIBLE "Hello" "World"
		SUM OF 3 AN 4
		
		FOUND YR PRODUKT OF X AN Y
		
	IF U SAY SO
	
	I IZ getPow YR 2 AN YR SUM OF 1 AN PRODUKT OF 5 AN 6 AN YR ALL OF 1 AN 2 AN 3 MKAY  AN YR 5 MKAY
	
KTHXBYE
