HAI
	I HAS A var1 ITZ 5
	I HAS A var2 ITZ 6
	I HAS A var3 ITZ 7
	
	HOW IZ I getPow YR X AN YR Y AN YR Z AN YR B
    	
		VISIBLE "Hello" "World"
		
		FOUND YR PRODUKT OF X AN Y
		
	IF U SAY SO
	
	VISIBLE I IZ getPow YR 2 AN YR var3 AN YR SUM OF 1 AN 2 AN YR 5 MKAY
	
	BTW I IZ getPow YR 2 AN YR SUM OF 1 AN PRODUKT OF 5 AN 6 AN YR ALL OF 1 AN 2 AN 3 MKAY  AN YR 5 MKAY
	BTW I IZ getPow YR 2 AN YR 3 AN YR 4 AN YR 5 MKAY
	BTW I IZ getPow MKAY
	
KTHXBYE
